"""
Versioned request DTOs received from Spring Boot.
These are the only objects FastAPI accepts from the outside world.
Spring Boot never sends raw LangGraph state.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from pydantic import BaseModel, Field


class ChatApiRequest(BaseModel):
    """DTO for POST /v1/chat — sent by Spring Boot."""

    request_id: str = Field(..., description="UUID generated by Spring Boot")
    query: str = Field(..., min_length=1, description="User query text")
    user_id: str = Field(..., description="Authenticated user ID from Spring Boot")
    session_id: Optional[str] = Field(None, description="Conversation session ID")


class DocumentApiRequest(BaseModel):
    """DTO for POST /v1/documents/analyze — sent by Spring Boot."""

    request_id: str = Field(..., description="UUID generated by Spring Boot")
    file_path: str = Field(..., description="Absolute path to the uploaded file")
    filename: str = Field(..., description="Original filename")
    extension: str = Field(..., description="File extension e.g. pdf, docx")
    mime_type: str = Field(..., description="MIME type of the file")
    size_bytes: int = Field(..., gt=0, description="File size in bytes")
    checksum: Optional[str] = Field(None, description="SHA-256 checksum")
    user_id: str = Field(..., description="Authenticated user ID from Spring Boot")


class KnowledgeApiRequest(BaseModel):
    """DTO for POST /v1/knowledge/upload — sent by Spring Boot."""

    request_id: str = Field(..., description="UUID generated by Spring Boot")
    file_path: str = Field(..., description="Absolute path to the uploaded file")
    filename: str = Field(..., description="Original filename")
    extension: str = Field(..., description="File extension e.g. pdf, docx")
    mime_type: str = Field(..., description="MIME type of the file")
    size_bytes: int = Field(..., gt=0, description="File size in bytes")
    checksum: Optional[str] = Field(None, description="SHA-256 checksum")
    user_id: str = Field(..., description="Authenticated user ID from Spring Boot")